version: '3'

services:
   api:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      URL : mongodb+srv://Techfesta:P8179A5572@cluster0.ur2ijgx.mongodb.net/form?retryWrites=true&w=majority
      SECRET_KEY : TechfiestaP8179A5572Developer 
    volumes:
      - .:/usr/src/app   

      