version: '3'

services:
   api:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      URL : mongodb+srv://litakeatharva24:Atharva242003@techfiesta.bjfi13v.mongodb.net/TechfiestaRegisteration?retryWrites=true&w=majority
      SECRET_KEY : TechfiestaP8179A5572Developer 
    volumes:
      - .:/usr/src/app   
      - /usr/src/app/node_modules 

      